DefaultContentLanguage = "en"
baseURL = ""
languageCode = "en-gb"
summaryLength = 10
theme = "meghna-hugo"
title = "The Pork Shack"
[[menu.nav]]
URL = "contact-us"
name = "Contact"
weight = 3
[[menu.nav]]
URL = "dishes"
name = "Dishes"
weight = 1
[[menu.nav]]
URL = "about"
name = "About Us"
weight = 2
[params]
author = "Ant Villa Dean"
custom_css = ["css/custom.css"]
description = "Filipino Street Food & Catering"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
googleAnalitycsID = "Your ID"
home = "Home"
logo = "images/siteicon.png"
[params.banner]
bgImage = "images/slider/phillipines.jpg"
btn = true
btnText = "Find Out More"
btnURL = "#contact-us"
content = "Bringing you a taste of the phillipines with our delicious adobo pork dishes! Now proudly offering catering services for your next private event!"
enable = true
heading = ""
image = "images/logoText.png"
[params.counter]
bgImage = "images/backgrounds/wood1.jpg"
enable = true
[[params.counter.counterItem]]
count = "100%"
icon = "tf-ion-refresh"
title = "Environmentally Friendly"
[[params.counter.counterItem]]
count = "Healthy"
icon = "tf-ion-heart"
title = "and Vegan-friendly"
[[params.counter.counterItem]]
count = "Tasty"
icon = "tf-ion-thumbsup"
title = "and Different"
[[params.counter.counterItem]]
count = "100%"
icon = "tf-ion-coffee"
title = "Biodegrable Cups & Cultery"
[params.cta]
btnText = " Check out what we offer!"
btnURL = "#contact-us"
content = "When you book us all you need to do - tell us where we’re pitching and we do the rest!"
enable = true
title = "Street Food Catering"
[params.footer]
copyright = "The Pork Shack"
copyrightURL = ""
[[params.footer.socialIcon]]
icon = "tf-ion-social-facebook"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-twitter"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-instagram"
url = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
