DefaultContentLanguage = "en"
baseURL = ""
cloudinary_url = "https://res.cloudinary.com/the-pork-shack/image/upload"
languageCode = "en-gb"
summaryLength = 10
theme = "meghna-hugo"
title = "The Pork Shack"
[[menu.nav]]
URL = "takeaway"
name = "Takeaway"
weight = 1
[[menu.nav]]
URL = "about"
name = "About Us"
weight = 3
[[menu.nav]]
URL = "contact-us"
name = "Contact"
weight = 4
[params]
author = "Ant Villa Dean"
custom_css = ["css/custom.css"]
description = "Filipino Street Food & Catering"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
googleAnalitycsID = "UA-132764638-1"
home = "Home"
logo = "images/siteicon.png"
[params.banner]
bgImage = "images/slider/phillipines.jpg"
btn = true
btnText = "Takeaway Price and Menu"
btnURL = "#takeaway"
content = "During these strange times"
enable = true
heading = ""
image = "images/logoText.png"
[params.counter]
bgImage = "images/backgrounds/wood1.jpg"
enable = true
[[params.counter.counterItem]]
count = "100%"
icon = "tf-ion-refresh"
title = "Environmentally Friendly"
[[params.counter.counterItem]]
count = "Healthy"
icon = "tf-ion-heart"
title = "and Vegan-friendly"
[[params.counter.counterItem]]
count = "Tasty"
icon = "tf-ion-thumbsup"
title = "and Different"
[[params.counter.counterItem]]
count = "100%"
icon = "tf-ion-coffee"
title = "Biodegrable Cups & Cultery"
[params.cta]
btnText = "Contact us now!"
btnURL = "#contact-us"
content = "When you book us all you need to do is tell us where we’re pitching and we do the rest!"
enable = true
title = "Street Food Catering"
[params.footer]
copyright = "Antvd.space"
copyrightURL = "https://antvd.space"
[[params.footer.socialIcon]]
icon = "tf-ion-social-facebook"
url = "https://www.facebook.com/theporkshackUK/"
[[params.footer.socialIcon]]
icon = "tf-ion-social-twitter"
url = "https://twitter.com/ShackPork"
[[params.footer.socialIcon]]
icon = "tf-ion-social-instagram"
url = "https://www.instagram.com/theporkshack/"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
