---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: config.yml
  label: Configuration File
- type: directory
  path: data
  label: Page Information
  create: documents
  match: "**/*"
  new_doc_ext: yml
upload_dir: ''
public_path: https://res.cloudinary.com/the-pork-shack/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.55.6
